openapi: 3.0.3
info:
  title: Kubernetes Plugin
  description: A plugin for interacting with Kubernetes clusters using chat-based input.
  version: 1.0.0

paths:
  /get-command:
    get:
      summary: Gets a kubectl command from OpenAI GPT.
      parameters:
        - name: query
          in: query
          required: true
          description: The query to be sent to OpenAI GPT.
          schema:
            type: string
      responses:
        200:
          description: The kubectl command.
          content:
            text/plain:
              schema:
                type: string

  /execute-command:
    post:
      summary: Executes a kubectl command.
      parameters:
        - name: command
          in: body
          required: true
          description: The kubectl command to execute.
          schema:
            type: string
      responses:
        200:
          description: The output of the kubectl command.
          content:
            text/plain:
              schema:
                type: string